// <auto-generated />
using System;
using FootballTrackerData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballTrackerData.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20251203075324_AddTeamRelationships")]
    partial class AddTeamRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("FootballTrackerData.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpponentGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isHomeMatch")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("FootballTrackerData.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("FootballTrackerData.Models.PlayerMatchPerformance", b =>
                {
                    b.Property<int>("PlayerMatchPerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InjuryNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayersRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerMatchPerformanceId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("playerMatchPerformances");
                });

            modelBuilder.Entity("FootballTrackerData.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("FootballTrackerData.Models.Match", b =>
                {
                    b.HasOne("FootballTrackerData.Models.Team", "Team")
                        .WithMany("Match")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballTrackerData.Models.Player", b =>
                {
                    b.HasOne("FootballTrackerData.Models.Team", "Team")
                        .WithMany("Player")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballTrackerData.Models.PlayerMatchPerformance", b =>
                {
                    b.HasOne("FootballTrackerData.Models.Match", "Match")
                        .WithMany("PlayerPerformances")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballTrackerData.Models.Player", "Player")
                        .WithMany("Performances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballTrackerData.Models.Match", b =>
                {
                    b.Navigation("PlayerPerformances");
                });

            modelBuilder.Entity("FootballTrackerData.Models.Player", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("FootballTrackerData.Models.Team", b =>
                {
                    b.Navigation("Match");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
